version: '3.5'

volumes:
  dbdata:

services:
  nginx:
    image: nginx:1.13
    container_name: nginx
    volumes:
      - ./backend:/var/www/backend
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    restart: always
    ports:
      - 8090:80
      - "443:443"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - nginx
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "30001:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'

  db:
    image: mysql:5.7.22
    container_name: db
    restart: always
    ports:
      - "33061:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - TZ=UTC
